name: Update Base Branch Command
on:
  issue_comment:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      github.event.issue.pull_request != '' &&
      (
        contains(github.event.comment.body, '/update')
      )
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history so we can merge branches
      - name: Fetch All Branches
        run: git fetch --all
      - name: Merge From Next
        run: git merge origin/next --strategy-option=theirs
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
